server:
  port: 9000
management:
  port: 9001
  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mydb
    username: postgres
    password: postgres

eureka:
  client:
    healthcheck:
      enabled: true   
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/

logging:
  file: sysout.log